# Generated by Django 5.0.7 on 2024-08-05 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('due', 'Pending'), ('done', 'Completed')], default='due', max_length=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('due_date', models.DateField()),
                ('posted_by', models.CharField(default='Anonymous', max_length=26)),
                ('avator', models.ImageField(default='a.png', upload_to='profiles/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapp.author')),
                ('tag', models.ManyToManyField(related_name='tasks', to='tapp.tag')),
            ],
        ),
    ]
