# Generated by Django 5.0.7 on 2024-08-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='posted_by',
        ),
    ]
