# Generated by Django 5.0.7 on 2024-09-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0002_remove_task_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='avator',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
